Recover segment list and modify method for adding segment
104corp/xray-laravel pull request #20
Opened 2021-10-15 09:40 UTC by HarkuLi

2021-10-15 09:49 UTC, HarkuLi commented on src/Collectors/JobCollector.php
> +    private function handleJobEnded(bool $success): void
這 method 看起來不用開 public

2021-10-15 09:49 UTC, HarkuLi commented on src/Collectors/RouteCollector.php
>              }
這個 catch exception 我不確定有沒有必要做
我看原 repo 是沒做
而且預想情況下，套件程式沒寫錯的話，應該是不會有 exception

2021-10-18 02:05 UTC, evan361425 requested changes
SegmentCollector 的問題比較需要討論，找時間來討論？

2021-10-18 02:05 UTC, evan361425 commented on src/Collectors/RouteCollector.php
> -                    ->end();
這裡會補個 `end` 是因為 Laravel 有時會沒有 fire `RequestHandled` 這個 event。

`end` 的功能只是增加 endTime，重複呼叫也只是覆蓋先前的 endTime。
相反，如果這個 segment 沒有 endTime，會讓整個 trace 被判斷有錯，就無法送出到 x-ray，所以這裏才補個 `end`

2021-10-18 02:05 UTC, evan361425 commented on src/Collectors/RouteCollector.php
>              }
OK 這裡的 try-catch 是因為 `getController` 裡面有對 `route` 的函示做呼叫，不確定不同版本的差異和影響才這樣加的。

2021-10-18 03:42 UTC, HarkuLi commented on src/Collectors/RouteCollector.php
> -                    ->end();
感謝說明，已修正

2021-10-18 03:44 UTC, merged